### ISSUE TITLE
Failing to build IOS

### ISSUE THREAD

**Issue by sharmavipul9756** [FormidableLabs/react-native-owl#139]
The following build commands failed:
        CodeSign /Users/vipulsharma/Library/CloudStorage/OneDrive-BajajFinanceLimited/Desktop/HRx_portal/HRx_portal/ios/build/Build/Products/Debug-iphonesimulator/VoipNotification\ UAT.appex (in target 'VoipNotification UAT' from project 'HrxMobileApp')
(1 failure)
Error: Command failed with exit code 65: xcodebuild -workspace ios/HrxMobileApp.xcworkspace -scheme HrxMobileAppUAT -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build
    at makeError (/Users/vipulsharma/Library/CloudStorage/OneDrive-BajajFinanceLimited/Desktop/HRx_portal/HRx_portal/node_modules/react-native-owl/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/vipulsharma/Library/CloudStorage/OneDrive-BajajFinanceLimited/Desktop/HRx_portal/HRx_portal/node_modules/react-native-owl/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  shortMessage: 'Command failed with exit code 65: xcodebuild -workspace ios/HrxMobileApp.xcworkspace -scheme HrxMobileAppUAT -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
  command: 'xcodebuild -workspace ios/HrxMobileApp.xcworkspace -scheme HrxMobileAppUAT -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
  escapedCommand: 'xcodebuild -workspace "ios/HrxMobileApp.xcworkspace" -scheme HrxMobileAppUAT -configuration Debug -sdk iphonesimulator -derivedDataPath "ios/build"',
  exitCode: 65,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Specify --help for available options
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by g-tiwari** [comment]
I am also seeing the same issue, my project uses React Native version - 0.71.2
is it yet supported ?

**Comment by robwalkerco** [comment]
I've just tested react-native-owl on React-Native 0.71 and the build works fine.

I am running into an issue running the jest tests on my example, but that is a separate issue from the one reported here.

**Comment by g-tiwari** [comment]
Thanks for the update. There might be some other issue then.
