### ISSUE TITLE
Owl build command create a debug build type

### ISSUE THREAD

**Issue by retyui** [FormidableLabs/react-native-owl#98]
- `yarn owl build --platform android` will create a debug build by default:

![image](https://user-images.githubusercontent.com/4661784/173227917-b571cec0-c45c-4a2d-87ae-e0d2860d16ae.png)

My config:

```json
{
  "android": {
    "packageName": "com.myowl",
  }
}
```

- Version:

```json
"react-native-owl": "^0.0.4",
```

**Comment by retyui** [comment]
I tried to update `buildCommand`:

```json
{
  "debug": true,
  "android": {
    "packageName": "com.myowl",
    "buildCommand": "./gradlew assembleRelease"
  }
}
```

But it didn't help

```log
yarn run v1.22.17
$ /home/i/tmp/MyOwl/node_modules/.bin/owl build --platform android
[OWL] Building the app on android platform.
[OWL] Using the config file ./owl.config.json.
[OWL] Building the app with: ./gradlew assembleRelease.
Error: Command failed with ENOENT: ./gradlew assembleRelease
spawn ./gradlew ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ./gradlew',
  path: './gradlew',
  spawnargs: [ 'assembleRelease' ],
  originalMessage: 'spawn ./gradlew ENOENT',
  shortMessage: 'Command failed with ENOENT: ./gradlew assembleRelease\n' +
    'spawn ./gradlew ENOENT',
  command: './gradlew assembleRelease',
  escapedCommand: '"./gradlew" assembleRelease',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by retyui** [comment]
Also tried to change `buildType`:

```json
{
  "debug": true,
  "android": {
    "packageName": "com.myowl",
    "buildType": "release"
  }
}
```

It also failed: 

```
yarn run v1.22.17
$ /home/i/tmp/MyOwl/node_modules/.bin/owl build --platform android
#/properties/android/additionalProperties: should NOT have additional properties

Specify --help for available options
error Command failed with exit code 1.
```

**Comment by retyui** [comment]
Fixed in the next release: 
```tsx
yarn add -D react-native-owl@next
```
